import javax.swing.*;
import java.time.YearMonth;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class FrameHitungHari extends javax.swing.JFrame {

    /**
     * Creates new form FrameHitungHari
     */
    public FrameHitungHari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bln = new javax.swing.JComboBox<>();
        angka = new javax.swing.JSpinner();
        htng = new javax.swing.JButton();
        hsl = new javax.swing.JLabel();
        c1 = new com.toedter.calendar.JCalendar();
        c2 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Aplikasi Hitung Hari");

        bln.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        angka.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        angka.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                angkaStateChanged(evt);
            }
        });

        htng.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        htng.setText("Hitung");
        htng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htngActionPerformed(evt);
            }
        });

        hsl.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        hsl.setText("Hasil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hsl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(htng, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(angka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(352, 352, 352))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 72, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(htng)
                .addGap(18, 18, 18)
                .addComponent(hsl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void htngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htngActionPerformed
    try {
            // Mendapatkan bulan dan tahun dari JComboBox dan JSpinner
            int bulan = bln.getSelectedIndex() + 1; // Januari = 1, dst.
            int tahun = (int) angka.getValue();

            // Menggunakan LocalDate untuk menghitung jumlah hari dalam bulan dan tahun yang dipilih
            java.time.LocalDate tanggalDariComboBox = java.time.LocalDate.of(tahun, bulan, 1);
            int jumlahHariDariComboBox = tanggalDariComboBox.lengthOfMonth();

            // Mendapatkan hari pertama dan terakhir dalam bulan tersebut
            java.time.LocalDate hariPertama = tanggalDariComboBox.withDayOfMonth(1);
            java.time.LocalDate hariTerakhir = tanggalDariComboBox.withDayOfMonth(jumlahHariDariComboBox);

            // Mengecek apakah tahun kabisat
            boolean isKabisat = java.time.Year.of(tahun).isLeap();

            // Mengambil tanggal dari JCalendar pertama (jCalendar1) untuk selisih hari
            java.util.Date selectedDate1 = c1.getDate();
            java.util.Date selectedDate2 = c2.getDate();
            long selisihHari = 0;

            // Menghitung selisih hari jika kedua tanggal dipilih
            if (selectedDate1 != null && selectedDate2 != null) {
                java.time.LocalDate tanggal1 = selectedDate1.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                java.time.LocalDate tanggal2 = selectedDate2.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                selisihHari = java.time.temporal.ChronoUnit.DAYS.between(tanggal1, tanggal2);
            }

            // Menampilkan hasil di JLabel
            String hasil = "Jumlah hari: " + jumlahHariDariComboBox +
                           "\n, Hari pertama: " + hariPertama.getDayOfWeek() +
                           "\n, Hari terakhir: " + hariTerakhir.getDayOfWeek() +
                           "\n, Tahun Kabisat: " + (isKabisat ? "Ya" : "Tidak");

            if (selectedDate1 != null && selectedDate2 != null) {
                hasil += "\n, Selisih hari antara kedua tanggal: " + Math.abs(selisihHari) + " hari";
            }

            hsl.setText(hasil);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Input tidak valid.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_htngActionPerformed

    private void angkaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_angkaStateChanged
      // Mendapatkan tahun yang baru diubah dari JSpinner
        int tahun = (int) angka.getValue();

        // Mendapatkan bulan yang dipilih dari JComboBox
        int bulan = bln.getSelectedIndex() + 1; // Januari = 1, dst.

        // Menggunakan LocalDate untuk mendapatkan jumlah hari dalam bulan dan tahun yang baru
        java.time.LocalDate tanggal = java.time.LocalDate.of(tahun, bulan, 1);
        int jumlahHari = tanggal.lengthOfMonth();

        // Menampilkan hasil jumlah hari di JLabel setiap kali tahun diubah
        hsl.setText("Jumlah hari: " + jumlahHari);
    }//GEN-LAST:event_angkaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameHitungHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner angka;
    private javax.swing.JComboBox<String> bln;
    private com.toedter.calendar.JCalendar c1;
    private com.toedter.calendar.JCalendar c2;
    private javax.swing.JLabel hsl;
    private javax.swing.JButton htng;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
